ROOM = "room"

ROOM_1 = "room-1"
ROOM_2 = "room-2"
ROOM_3 = "room-3"

APPLE = "apple"
BLUE = "blue"
COIN = "coin"
COPPER = "copper"
DOOR = "door"
GEM = "gem"
KEY = "key"
LIBRARY = "library"
PLAYER = "player"
RED = "red"
ROCK = "rock"
ROTUNDA = "rotunda"
SILVER = "silver"
STATUE = "statue"
STONE = "stone"
THING = "thing"
TREASURE = "treasure"
WOODEN = "wooden"
ZEBRA = "zebra"

ROOM_DESCRIPTION = "A round stone chamber."
COPPER_COIN_DESCRIPTION = "A dull copper coin."
SILVER_COIN_DESCRIPTION = "A bright silver coin."
